networks:
  server:
    external: true
services:
  emby:
    container_name: emby
    image: emby/embyserver:latest
    restart: always
    environment:
      - GID=${GID}
      - GIDLIST=985,989 # video,render
      - TZ=${TZ}
      - UID=${UID}
    volumes:
      - ./emby:/config
      - /mnt/shared/Media:/mnt/shared/Media
    ports:
      - 8096:8096
      - 1900:1900
    networks:
      - server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest      
    restart: always
    user: ${UID}:${GID}
    ports:
      - 5055:5055
    networks:
      - server
    volumes:
      - ./jellyseerr:/app/config
    environment:
      - JELLYFIN_TYPE=emby
      - TZ=${TZ}
  nzbget:
    container_name: nzbget
    image: mouton99/nzbget-ng:latest
    restart: always
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ./nzbget:/config
      - /mnt/downloads:/mnt/downloads
      - /mnt/shared/Downloads:/mnt/shared/Downloads
    ports:
      - 6789:6789
    networks:
      - server
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: always
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - server
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: always
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - /mnt/shared:/mnt/shared
    ports:
      - 7878:7878
    networks:
      - server
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:nightly
    restart: always
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - /mnt/shared:/mnt/shared
    ports:
      - 8989:8989
    networks:
      - server
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: always
    ports:
      - 5690:5690
    networks:
      - server
    volumes:
      - ./wizarr:/data/database
    environment:
      - TZ=${TZ}
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: ${UID}:${GID}
    ports:
      - 4533:4533
    networks:
      - server
    restart: always
    environment:
      - ND_CONFIGFILE=/data/navidrome.toml
      - TZ=${TZ}
    volumes:
      - ./navidrome:/data
      - /mnt/shared/Media/Music:/music:ro
